name: Publish to hugging face datatset

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python main.py --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }}

      - name: Publish to hugging face dataset
        run: |
          pip install huggingface-hub
          huggingface-cli login --token ${{ secrets.HF_TOKEN }}
          huggingface-cli upload cloudy-sfu/Gaspy results --repo-type=dataset
