name: Daily Price Monitor

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python main.py --github_action --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }}

      - name: Commit data to data branch
        run: |
          DATE=$(date +'%Y-%m-%d')
          MONTH=$(date +'%Y-%m')
          if [ ! -f "/tmp/$DATE.csv" ]; then
            echo "File /tmp/$DATE.csv does not exist. Aborting."
            exit 1
          fi
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --depth=1 origin data
          git switch -c data origin/data || git switch --orphan data
          mkdir -p "$MONTH"
          cp "/tmp/$DATE.csv" "$MONTH/$DATE.csv"
          git add "$MONTH/$DATE.csv"
          git commit -m "Add data on $DATE" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_PUSH }}@github.com/${{ github.repository }} data
